name: Add Core
description: Add a new core
title: "[New Core]: "
body:
  - type: input
    id: github-username
    attributes:
      label: GitHub Username
      description: The owner of the GitHub repository where the openFPGA core is hosted.
      placeholder: e.g. spiritualized1997
    validations:
      required: true
  - type: input
    id: repostiory-name
    attributes:
      label: Repository Name
      description: The name of the GitHub repository where the openFPGA core is hosted.
      placeholder: e.g. openFPGA-GB-GBC
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### GitHub Release Options

        > [NOTE!]
        > If the openFPGA core is distributed via GitHub releases (excluding pre-release) as a *single* asset, no further options are required.
  - type: checkboxes
    id: options-prerelease
    attributes:
      label: Pre-release
      description: Select this option if the GitHub release containing the openFPGA core has been labeled as a pre-release.
      options:
        - label: The GitHib release which contains the openFPGA core is labeled as a pre-release.
  - type: input
    id: options-filter
    attributes:
      label: Asset Filter
      description: Specify a RegEx pattern if the GitHub release contains multiple assets to narrow the selection.
      placeholder: e.g. Spiritualized_GB_
  - type: markdown
    attributes:
      value: |
        ### Repository File Options
  - type: input
    id: options-path
    attributes:
      label: Path
      description: Specify the path to the file if the openFPGA core is distributed as a repository file.
      placeholder: e.g. pocket/zips/jotego.jtcps1.zip
